# this doesn't work
# {% set data = load_setup_py_data() %}

package:
  name: {{ environ.get('CONDA_PKG') }}
  version: {{ environ.get('CONDA_PKG_VERSION') }}

source:
    path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - dominate
    - jinja2
    - libsass
    - numpy
    - pandas
    - pydantic<2.0.0
    - scipy
    - seaborn~=0.12.0
    - sigfig
    - bokeh~=3.1.0
    - natsort==8.4.0
    - pysam
    - pymsaviz==0.5.0
    - biopython==1.86
    - setuptools # required for runtime use of pkg_resources
    - si-prefix==1.3.3

test:
  imports:
    - ezcharts

about:
  home: "https://github.com/epi2me-labs/ezcharts"
  license: Mozilla Public License 2.0 
  license_family: OTHER
  license_file: LICENSE
  summary: "eCharts plotting API"
  doc_url: https://github.com/epi2me-labs/ezcharts
  dev_url: https://github.com/epi2me-labs/ezcharts

extra:
  recipe-maintainers:
    - cjw85

